{{/*
Wrapper helpers, prefixed okdp-rustfs. so they never collide with the partials
of the vendored charts (rustfs.*, oidc-dcr's).
*/}}

{{/*
Instance name: the release name without its project prefix. Hosts derive from
it, never from the product name, so a store deployed under a neutral name
takes over that name's hosts (instance "storage" in "default" serves
storage-default). The console prefixes instances with their project, which
would double the namespace: it is stripped.
*/}}
{{- define "okdp-rustfs.instance" -}}
{{- trimPrefix (printf "%s-" .Release.Namespace) .Release.Name -}}
{{- end -}}

{{/* Console host: <consoleHost>.<suffix>, default <instance>-<namespace>.<suffix>. */}}
{{- define "okdp-rustfs.consoleHost" -}}
{{- include "okdp.require" (dict "ctx" . "keys" (list "ingress.suffix")) -}}
{{- if .Values.consoleHost -}}
{{- printf "%s.%s" .Values.consoleHost .Values.global.okdp.ingress.suffix -}}
{{- else -}}
{{- include "okdp.ingressHost" (dict "ctx" . "name" (include "okdp-rustfs.instance" .)) -}}
{{- end -}}
{{- end -}}

{{/* S3 API host: <apiHost>.<suffix>, default <instance>-<namespace>-api.<suffix>. */}}
{{- define "okdp-rustfs.s3Host" -}}
{{- include "okdp.require" (dict "ctx" . "keys" (list "ingress.suffix")) -}}
{{- if .Values.apiHost -}}
{{- printf "%s.%s" .Values.apiHost .Values.global.okdp.ingress.suffix -}}
{{- else -}}
{{- printf "%s-%s-api.%s" (include "okdp-rustfs.instance" .) .Release.Namespace .Values.global.okdp.ingress.suffix -}}
{{- end -}}
{{- end -}}

{{/* Image tag of the server, also run by the provisioning Job (curl). */}}
{{- define "okdp-rustfs.imageTag" -}}1.0.0{{- end -}}

{{/* Service of the server (upstream naming, fullnameOverride = release). */}}
{{- define "okdp-rustfs.service" -}}
{{- printf "%s-svc" .Release.Name -}}
{{- end -}}

{{/* In-cluster S3 endpoint. */}}
{{- define "okdp-rustfs.internalUrl" -}}
{{- printf "http://%s.%s.svc.cluster.local:9000" (include "okdp-rustfs.service" .) .Release.Namespace -}}
{{- end -}}

{{/*
Secret holding the root identity (RUSTFS_ACCESS_KEY/RUSTFS_SECRET_KEY):
<release>-root, generated by ESO, unless rootSecretKey is set, in which case
the upstream chart writes <release>-secret from the values.
*/}}
{{- define "okdp-rustfs.rootSecret" -}}
{{- if .Values.rootSecretKey -}}
{{- printf "%s-secret" .Release.Name -}}
{{- else -}}
{{- include "okdp.fullname" (dict "ctx" . "suffix" "root") -}}
{{- end -}}
{{- end -}}

{{/*
Credentials Secret of the s3 output (accessKey/secretKey): outputSecretRef when
set (an identity of the store, a grant), else <release>-s3-credentials,
generated by ESO and provisioned by the chart.
*/}}
{{- define "okdp-rustfs.credentialsSecret" -}}
{{- .Values.outputSecretRef | default (include "okdp.fullname" (dict "ctx" . "suffix" "s3-credentials")) -}}
{{- end -}}

{{/* Secret of the OAuth client (client_id/client_secret), when the platform does not register it (existing mode). */}}
{{- define "okdp-rustfs.oauthSecret" -}}
{{- printf "creds-%s-oauth2" .Release.Name -}}
{{- end -}}

{{/* Secret the oidc-dcr job writes the registered client to (dcr mode), same keys. */}}
{{- define "okdp-rustfs.dcrSecret" -}}
{{- printf "%s-%s-dcr" .Release.Name .Release.Namespace -}}
{{- end -}}

{{/*
OIDC settings, as YAML: enabled, the OAuth client Secret, the discovery URL,
the scopes (platform scopes plus oidcPolicyScope, comma separated), the
issuer origin (the server's SSRF guard refuses private origins unless
allowed) and the display name.
*/}}
{{- define "okdp-rustfs.oidc" -}}
{{- $oidc := include "okdp.oidc" . | fromYaml -}}
{{- $out := dict "enabled" $oidc.enabled -}}
{{- if $oidc.enabled -}}
  {{- include "okdp.require" (dict "ctx" . "keys" (list "oidc.issuerUri")) -}}
  {{- $scope := $oidc.scope -}}
  {{- with .Values.oidcPolicyScope }}{{ $scope = printf "%s %s" $scope . }}{{ end -}}
  {{- $parts := splitList "/" $oidc.issuerUri -}}
  {{- $secret := include "okdp-rustfs.oauthSecret" . -}}
  {{- if $oidc.dcr.enabled }}{{ $secret = include "okdp-rustfs.dcrSecret" . }}{{ end -}}
  {{- $_ := set $out "secret" $secret -}}
  {{- $_ := set $out "discoveryUrl" (printf "%s/.well-known/openid-configuration" $oidc.issuerUri) -}}
  {{- $_ := set $out "scopes" ($scope | replace " " ",") -}}
  {{- $_ := set $out "origin" (printf "%s//%s" (index $parts 0) (index $parts 2)) -}}
  {{- $_ := set $out "displayName" ($oidc.displayName | default "keycloak") -}}
  {{- $_ := set $out "redirectUri" (printf "https://%s/rustfs/admin/v3/oidc/callback/default" (include "okdp-rustfs.consoleHost" .)) -}}
{{- end -}}
{{- toYaml $out -}}
{{- end -}}

{{/*
okdp-rustfs.statements: IAM statements for neutral verbs on buckets, as a
YAML list. Takes {verbs, buckets, admin}. Verbs are matched case-insensitively:
the same grants block applies to any store backend, whatever casing its own
chart documents. RustFS rejects s3: and admin: actions mixed in one statement.
*/}}
{{- define "okdp-rustfs.statements" -}}
{{- $verbMap := dict
    "read"  (list "s3:GetObject" "s3:GetBucketLocation")
    "list"  (list "s3:ListBucket" "s3:ListAllMyBuckets")
    "write" (list "s3:PutObject" "s3:DeleteObject" "s3:AbortMultipartUpload") -}}
{{- $resources := list -}}
{{- range $b := (.buckets | default (list "*")) -}}
  {{- if eq $b "*" }}{{ $resources = concat $resources (list "arn:aws:s3:::*" "arn:aws:s3:::*/*") }}
  {{- else }}{{ $resources = concat $resources (list (printf "arn:aws:s3:::%s" $b) (printf "arn:aws:s3:::%s/*" $b)) }}{{ end -}}
{{- end -}}
{{- if .admin -}}
{{- toYaml (list (dict "Effect" "Allow" "Action" (list "s3:*") "Resource" ($resources | uniq)) (dict "Effect" "Allow" "Action" (list "admin:*") "Resource" (list "arn:aws:s3:::*"))) -}}
{{- else -}}
{{- $actions := list -}}
{{- range $v := .verbs }}{{ with (index $verbMap $v) }}{{ $actions = concat $actions . }}{{ end }}{{ end -}}
{{- toYaml (list (dict "Effect" "Allow" "Action" ($actions | uniq) "Resource" ($resources | uniq))) -}}
{{- end -}}
{{- end -}}

{{/* Lower-cased verbs of a grant or policy: {actions} -> YAML list. */}}
{{- define "okdp-rustfs.verbs" -}}
{{- $verbs := list -}}
{{- range $v := (.actions | default list) }}{{ $verbs = append $verbs (lower $v) }}{{ end -}}
{{- toYaml $verbs -}}
{{- end -}}
