{{/*
Values of the vendored charts: the former KuboCD module `values:` templates,
with .Context -> .Values.global.okdp and .Parameters -> .Values. The ingresses
and the provisioning job, formerly upstream extraManifests, are templates of
this chart (ingress.yaml, provision.yaml); the OIDC provider, formerly
registered by that job (mc admin config set), is set in the environment.
*/}}

{{/* Module main: the rustfs chart. */}}
{{- define "okdp-rustfs.values.rustfs" -}}
{{- include "okdp.require" (dict "ctx" . "keys" (list "ingress.suffix" "ingress.className" "certificateIssuers.selfSigned.name" "storageClass.data")) -}}
{{- $oidc := include "okdp-rustfs.oidc" . | fromYaml -}}
nameOverride: {{ .Release.Name }}
fullnameOverride: {{ .Release.Name }}
# Single node (standalone).
mode:
  standalone:
    enabled: true
  distributed:
    enabled: false
replicaCount: 1
resources:
  requests:
    cpu: {{ .Values.cpu | quote }}
    memory: 512Mi
  limits:
    cpu: {{ mulf (float64 .Values.cpu) 2 | quote }}
    memory: {{ printf "%vGi" .Values.memoryGi | quote }}
storageclass:
  name: {{ .Values.global.okdp.storageClass.data | quote }}
  dataStorageSize: {{ .Values.dataStorage | quote }}
  logStorageSize: 256Mi
secret:
{{- if .Values.rootSecretKey }}
  rustfs:
    access_key: {{ .Values.rootAccessKey | quote }}
    secret_key: {{ .Values.rootSecretKey | quote }}
{{- else }}
  # Generated by ESO (root-secret.yaml).
  existingSecret: {{ include "okdp-rustfs.rootSecret" . }}
{{- end }}
image:
  rustfs:
    tag: {{ include "okdp-rustfs.imageTag" . | quote }}
{{- if $oidc.enabled }}
# Sign-in on the console: the default provider, read from the environment at
# startup (a provider whose discovery fails then stays off until a restart).
extraEnv:
  - name: RUSTFS_BROWSER_REDIRECT_URL
    value: {{ printf "https://%s" (include "okdp-rustfs.consoleHost" .) | quote }}
  # The SSRF guard refuses any origin that resolves to a private address.
  - name: RUSTFS_OUTBOUND_ALLOW_ORIGINS
    value: {{ $oidc.origin | quote }}
  - name: SSL_CERT_FILE
    value: /cacerts/ca.crt
  - name: RUSTFS_IDENTITY_OPENID_ENABLE
    value: "on"
  - name: RUSTFS_IDENTITY_OPENID_CONFIG_URL
    value: {{ $oidc.discoveryUrl | quote }}
  - name: RUSTFS_IDENTITY_OPENID_CLIENT_ID
    valueFrom: {secretKeyRef: {name: {{ $oidc.secret }}, key: client_id}}
  - name: RUSTFS_IDENTITY_OPENID_CLIENT_SECRET
    valueFrom: {secretKeyRef: {name: {{ $oidc.secret }}, key: client_secret}}
  - name: RUSTFS_IDENTITY_OPENID_SCOPES
    value: {{ $oidc.scopes | quote }}
  - name: RUSTFS_IDENTITY_OPENID_REDIRECT_URI
    value: {{ $oidc.redirectUri | quote }}
  - name: RUSTFS_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC
    value: "off"
  - name: RUSTFS_IDENTITY_OPENID_DISPLAY_NAME
    value: {{ $oidc.displayName | quote }}
  - name: RUSTFS_IDENTITY_OPENID_CLAIM_NAME
    value: {{ .Values.oidcPolicyClaim | quote }}
  - name: RUSTFS_IDENTITY_OPENID_GROUPS_CLAIM
    value: {{ .Values.oidcPolicyClaim | quote }}
  - name: RUSTFS_IDENTITY_OPENID_USERNAME_CLAIM
    value: preferred_username
  - name: RUSTFS_IDENTITY_OPENID_EMAIL_CLAIM
    value: email
extraVolumes:
  - name: cacerts
    secret:
      secretName: {{ .Values.caBundleSecret }}
extraVolumeMounts:
  - name: cacerts
    mountPath: /cacerts
{{- end }}
# The upstream ingress targets the console port only: both ingresses (S3 API
# and console) are templates of this chart.
ingress:
  enabled: false
{{- end -}}

{{/* Module oidc-dcr: registers the OAuth client by anonymous Dynamic Client Registration. */}}
{{- define "okdp-rustfs.values.dcr" -}}
{{- $oidc := include "okdp.oidc" . | fromYaml -}}
{{- if ne ($oidc.dcr.authMethod | default "") "anonymous" -}}
  {{- fail (printf "rustfs: global.okdp.oidc.dcr.authMethod %q is not supported: this chart registers anonymously" ($oidc.dcr.authMethod | default "")) -}}
{{- end -}}
{{- include "okdp.require" (dict "ctx" . "keys" (list "oidc.dcr.registrationUrl")) -}}
{{- /* The policy claim rides its own scope, which the platform scopes do not carry. */ -}}
{{- $scope := $oidc.scope -}}
{{- with .Values.oidcPolicyScope }}{{ $scope = printf "%s %s" $scope . }}{{ end -}}
ttl_seconds: 30
registration_url: {{ $oidc.dcr.registrationUrl | quote }}
request:
  application_type: web
  # Named after what the DNS shows, not after the release.
  client_name: {{ printf "%s-%s" (include "okdp-rustfs.instance" .) .Release.Namespace | quote }}
  redirect_uris:
    - {{ printf "https://%s/rustfs/admin/v3/oidc/callback/default" (include "okdp-rustfs.consoleHost" .) | quote }}
  grant_types:
    - authorization_code
    - refresh_token
    - client_credentials
  scope: {{ without (splitList " " $scope) "openid" | join " " | quote }}
tls:
  insecure: false
  certificate: {{ .Values.caBundleSecret | quote }}
secret: {{ include "okdp-rustfs.dcrSecret" . }}
mapping:
  use_default: false
  key_mapping:
    client_id: ".client_id"
    client_secret: ".client_secret"
{{- end -}}
