{{/*
Computed values of the vendored rustfs chart (the fixed ones are in
vendor-values/rustfs.yaml): the former KuboCD module `values:` template, with
.Context -> .Values.global.okdp and .Parameters -> .Values. The ingresses
and the provisioning job, formerly upstream extraManifests, are templates of
this chart (ingress.yaml, provision.yaml); the OIDC provider, formerly
registered by that job (mc admin config set), is set in the environment.
*/}}

{{/* Module main: the rustfs chart. */}}
{{- define "okdp-rustfs.values.rustfs" -}}
{{- include "okdp.require" (dict "ctx" . "keys" (list "ingress.suffix" "ingress.className" "certificateIssuers.selfSigned.name" "storageClass.data")) -}}
{{- $oidc := include "okdp-rustfs.oidc" . | fromYaml -}}
nameOverride: {{ .Release.Name }}
fullnameOverride: {{ .Release.Name }}
resources:
  requests:
    cpu: {{ .Values.cpu | quote }}
  limits:
    cpu: {{ mulf (float64 .Values.cpu) 2 | quote }}
    memory: {{ printf "%vGi" .Values.memoryGi | quote }}
storageclass:
  name: {{ .Values.global.okdp.storageClass.data | quote }}
  dataStorageSize: {{ .Values.dataStorage | quote }}
secret:
{{- if .Values.rootSecretKey }}
  rustfs:
    access_key: {{ .Values.rootAccessKey | quote }}
    secret_key: {{ .Values.rootSecretKey | quote }}
{{- else }}
  # Generated by ESO (root-secret.yaml).
  existingSecret: {{ include "okdp-rustfs.rootSecret" . }}
{{- end }}
image:
  rustfs:
    tag: {{ include "okdp-rustfs.imageTag" . | quote }}
{{- if $oidc.enabled }}
# Sign-in on the console: the default provider, read from the environment at
# startup (a provider whose discovery fails then stays off until a restart).
extraEnv:
  - name: RUSTFS_BROWSER_REDIRECT_URL
    value: {{ printf "https://%s" (include "okdp-rustfs.consoleHost" .) | quote }}
  # The SSRF guard refuses any origin that resolves to a private address.
  - name: RUSTFS_OUTBOUND_ALLOW_ORIGINS
    value: {{ $oidc.origin | quote }}
  - name: SSL_CERT_FILE
    value: /cacerts/ca.crt
  - name: RUSTFS_IDENTITY_OPENID_ENABLE
    value: "on"
  - name: RUSTFS_IDENTITY_OPENID_CONFIG_URL
    value: {{ $oidc.discoveryUrl | quote }}
  - name: RUSTFS_IDENTITY_OPENID_CLIENT_ID
    valueFrom: {secretKeyRef: {name: {{ $oidc.secret }}, key: client_id}}
  - name: RUSTFS_IDENTITY_OPENID_CLIENT_SECRET
    valueFrom: {secretKeyRef: {name: {{ $oidc.secret }}, key: client_secret}}
  - name: RUSTFS_IDENTITY_OPENID_SCOPES
    value: {{ $oidc.scopes | quote }}
  - name: RUSTFS_IDENTITY_OPENID_REDIRECT_URI
    value: {{ $oidc.redirectUri | quote }}
  - name: RUSTFS_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC
    value: "off"
  - name: RUSTFS_IDENTITY_OPENID_DISPLAY_NAME
    value: {{ $oidc.displayName | quote }}
  - name: RUSTFS_IDENTITY_OPENID_CLAIM_NAME
    value: {{ .Values.oidcPolicyClaim | quote }}
  - name: RUSTFS_IDENTITY_OPENID_GROUPS_CLAIM
    value: {{ .Values.oidcPolicyClaim | quote }}
  - name: RUSTFS_IDENTITY_OPENID_USERNAME_CLAIM
    value: preferred_username
  - name: RUSTFS_IDENTITY_OPENID_EMAIL_CLAIM
    value: email
extraVolumes:
  - name: cacerts
    secret:
      secretName: {{ .Values.caBundleSecret }}
extraVolumeMounts:
  - name: cacerts
    mountPath: /cacerts
{{- end }}
{{- end -}}

{{/*
Instance-level upstream values (okdp-lib-chart okdp.vendor.render option
`upstream`): an instance sets any value of the vendored chart under
upstream.rustfs in its values.yaml, over the values computed above, except the
protected paths.
Protected: the names and ports the s3 connection, the provisioning Job and the
ingresses of this chart address (<release>-svc, 9000 and 9001); the root
identity (secret: the ESO-generated Secret the provisioning Job also reads);
the exposure, owned by this chart's ingresses (the console host is registered
with the identity provider): the upstream ingress and Gateway API routes; and
extraManifests (arbitrary objects through tpl, replaced by this chart's own
templates). Appended: the lists carrying the OIDC client Secret and the CA
bundle, so an instance adds to them.
*/}}
{{- define "okdp-rustfs.upstream.rustfs" -}}
protect:
  - nameOverride
  - fullnameOverride
  - service.endpoint.port
  - service.console.port
  - config.rustfs.address
  - config.rustfs.console_address
  - secret
  - ingress
  - gatewayApi
  - extraManifests
append:
  - extraEnv
  - extraVolumes
  - extraVolumeMounts
{{- end -}}
